title: Pretty Good Baby Gear
email: prettygoodbabygear@gmail.com
author: Learnable LLC
description: >-
  When you have a baby, you buy everything with the baby in mind.
  Every product becomes a baby product. You do extensive research, read
  blogs, reviews, ingredients, etc. Here are some recommendations.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
production_url: "https://prettygoodbabygear.com"
github_username:  mprat

# theme settings from jekyll-theme-yat
# copyright: "Copyright (c) 2022-{currentYear} {author}"
copyright: "Copyright (c) {currentYear} {author}"
google_analytics: "G-XDCBDET4C2"
# sitemap: false

# Build settings
remote_theme: "jeffreytse/jekyll-theme-yat"
plugins:
  - jekyll-feed
  - jekyll-remote-theme

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
